# Generated by Django 3.1.5 on 2021-01-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images', verbose_name='Image')),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('name_slug', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name slug')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is published?')),
                ('sale', models.CharField(blank=True, max_length=150, verbose_name='sale')),
                ('is_top', models.BooleanField(default=False, verbose_name='is top')),
            ],
        ),
    ]
