# Generated by Django 3.1.5 on 2021-01-20 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210120_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('1', '1 category'), ('2', '2 category'), ('3', '3 category'), ('4', '4 category'), ('5', '5 category')], default=django.utils.timezone.now, max_length=300, verbose_name='category'),
            preserve_default=False,
        ),
    ]
